### ISSUE TITLE
external_dependencies is empty

### ISSUE THREAD

**Issue by ZZWENG** [IGLICT/NeRFFaceLighting#1]
Hi thank you for the great work. In your instructions you said external_dependencies includes modified code, but the folder in this repo is a symlink and does not really contain anything. Could you share the modified code? Thanks!

**Comment by RaymondJiangkw** [comment]
Hi, that folder `eg3d/external_dependencies` points to the folder `projector/external_dependencies`. You can find the relevant code under the `projector` sub-directory.
It has something to do with how git deals with the symbolic links. I will correct them soon. But, currently, all symbolic links in this repository should point to something already exist. Please check each sub-directory under the root first.
