### ISSUE TITLE
When I run "from external_dependencies.DPR import DPR",it was error

### ISSUE THREAD

**Issue by zyhsweety** [IGLICT/NeRFFaceLighting#4]
Dear sir

**Comment by zyhsweety** [comment]
The error is :
ImportError: cannot import name 'DPR' from 'external dependencies.DPR' (unknown location)

But I have taken DPR.pth in the folder "./external_dependencies/DPR/DPR.pth"

**Comment by RaymondJiangkw** [comment]
Hi!

Sorry… There was an issue with the soft link. Please manually link the ‘external_dependencies’ under the ‘eg3d’ folder to that under the ‘projector’ folder.

On Nov 17, 2023, at 06:16, zyh sweety ***@***.***> wrote:

﻿

The error is :
ImportError: cannot import name 'DPR' from 'external dependencies.DPR' (unknown location)

But I have taken DPR.pth in the folder "./external_dependencies/DPR/DPR.pth"
